#!/usr/bin/python
import os
import sys

from zvshlib import zvsh

zvsh_args = zvsh.ZvArgs()
zvsh_args.parse(sys.argv[1:])
zvsh_config = ['zvsh.cfg',
               os.path.expanduser('~/.zvsh.cfg'),
               '/etc/zvsh.cfg']
config = zvsh.ZvConfig()
config.read(zvsh_config)
if 'gdb' == zvsh_args.args.command:
    # user wants to debug the program
    zvsh_args = zvsh.DebugArgs()
    zvsh_args.parse(sys.argv[1:])
    zvshell = zvsh.ZvShell(config, zvsh_args.args.zvm_save_dir)
    # a month until debug session will time out
    zvshell.config['manifest']['Timeout'] = 60 * 60 * 24 * 30
    manifest_file = zvshell.add_arguments(zvsh_args.args)
    zvm_run = ['zerovm-dbg', '-sPQ', manifest_file]
    command_line = ['x86_64-nacl-gdb',
                    '--command=%s' % zvshell.add_debug_script()]
    command_line.extend(zvsh_args.args.gdb_args)
    command_line.append('--args')
    command_line.extend(zvm_run)
    print ' '.join(command_line)
    try:
        zvsh.spawn(command_line)
    except (KeyboardInterrupt, Exception):
        pass
    finally:
        zvshell.cleanup()
else:
    zvsh.run_zerovm(config, zvsh_args)
